### ISSUE TITLE
[Device] Will this control a Fanlinc and Keypadlinc?

### ISSUE THREAD

**Issue by brendanjerwin** [automategreen/home-controller#22]
I've successfully controlled a Switchlinc dimmer and utilized a motion sensor with the library. Its not immediately apparent how I would control a Fanlinc though. Any guidance?

**Comment by brandongoode** [comment]
It can control any Insteon device, but not all devices have user-friendly wrappers.  How exactly would you like to control them?

**Comment by brendanjerwin** [comment]
The Fanlinc exposes a fan half, with off, low, medium, high, and a light dimmer half. 

The KeypadLinc has the bunch of dimmer controllers and the status lights.

I want to expose all the Fanlinc bits in nice classes and I want to force the Keypadlinc status buttons to follow the Fanlinc status.

**Comment by brandongoode** [comment]
@brendanjerwin - I've added the fan control to the light class.  I was going to create a new class, but, since the 1st group on the FanLinc is the dimmer, I just extended the light class.  I don't have a FanLinc. Would you be able to verify it works correctly?

### Fan Functions

Fan functions are part of the light class.  The FanLinc is more or less a dimmer with fan control.  All the normal dimmer controls work the same.

#### light.fanOn([callback]), light.fanMedium([callback]), light.fan('medium', [callback])

Turn the fan on to medium speed

#### light.fanOff([callback]), light.fan('off', [callback])

Turn the fan off

#### light.fanLow([callback]), light.fan('low', [callback])

Turn the fan on to low speed

#### light.fanHigh([callback]), light.fan('high', [callback])

Turn the fan on to high speed

**Comment by brendanjerwin** [comment]
Doesn't seem to be working. https://gist.github.com/brendanjerwin/843f16e01cee7d70b5a6
Device is: 27F830

It's not paired with the PLM though, that requires taking the fan off the ceiling... (there really should be a better way.) It should still respond to commands though, right? It just won't send status updates?

**Comment by brendanjerwin** [comment]
OK, I paired with it (with an Indigo trial) and it seems to be able to turn off now. 
`fanLow` seems to put it into an unknown state as does `fanMedium`.
`fanHigh` seems to work.

**Comment by brandongoode** [comment]
Thanks for testing it.  Insteon documentation and the actual behavior or never quite the same. 

Most Insteon devices will ignore (most) command from devices not in their linking database.  You can use the [linking function](https://github.com/automategreen/home-controller#linking-functions) to link the devices too.

Can you provide the debug output from the fanMedium and fanLow?

**Comment by brendanjerwin** [comment]
`fanLow` = https://gist.github.com/brendanjerwin/9544b0a4b1a5e3b8a5a6
`fanMedium` = https://gist.github.com/brendanjerwin/970c69a19514e969a5b6

**Comment by brandongoode** [comment]
Thanks.  The device isn't responding to the commands 'on' levels (0x10 and 0x80).  I'll dig into this evening.

**Comment by brandongoode** [comment]
@brendanjerwin  - When you get a chance, please see if the low and medium are working now.

**Comment by brendanjerwin** [comment]
Still strange behavior for both:

`fanMedium` - https://gist.github.com/brendanjerwin/199da28d12bdad9c2fc5
`fanLow` - https://gist.github.com/brendanjerwin/704fb4df03ff7d3e08e0

Perhaps we can set up some way for you to iterate quicker? I'd be willing to do some screen sharing and/or see if I can set you up an account on one of my machines to get access to this hardware.

**Comment by brandongoode** [comment]
Can you describe the strange behavior?  Does the fans speed change but the `fanMedium()` call fails?  I asked because it looks like the FanLinc is responding with and ACK (025027f8301cf7762711bf - for the fanMedium), but doesn't respond with the expected extended command.  This can be change easily, if this is the case.

I agree, this is a bit of a pain.  If we can't resolve it soon, we'll set something up directly to troubleshoot.

**Comment by brendanjerwin** [comment]
The status reported is none of the expected statuses. So, for instance, the Insteon Hub app shows all the speed options (including "off") as inactive. Under normal usage, of course, _one_ of those options is always set.

**Comment by brandongoode** [comment]
First - sorry this is taking so long to get this working and thanks for helping.

The Hub app may not actually be checking the status.  Sometime it caches the last value it set.  

I've added the ability to query the FanLinc for the current speed.  It's based on what Insteon has documented so it may or may not work.  Can you use it to query the FanLinc after setting it. Also, you could try setting the fan speed with the Hub app then checking the speed.

To query the speed, call the `.fan()` function without any arguments.  It will return either 'off', 'high', 'medium', or 'low'.

**Comment by brandongoode** [comment]
Closing.  Release v0.6.0 contains the FanLinc functionality.
