### ISSUE TITLE
Homekit support

### ISSUE THREAD

**Issue by bradgessler** [automategreen/home-controller#73]
I'd be interested in a Homekit integration of this `home-controller` lib via a homebridge plugin. Details at https://github.com/nfarina/homebridge. Specifically I have a PLM and would like to not have to purchase the "Insteon Hub Pro" because of its poor reviews and reliability issues.

**Comment by siburny** [comment]
It looks like you would have to create a plug-in for homebridge that uses our library to talk to Insteon network.

**Comment by bradgessler** [comment]
Yeah, sorry, I could have been more clear about that. I opened this issue to gauge interest around this integration, specifically do the maintainers or contributors of this library have plans to integrate a homebrige integration or know of any efforts currently underway? If not I’m hoping to document that here and close the issue so others know they wouldn’t be duplicating any efforts.

Thanks!

**Comment by kuestess** [comment]
If you have an API key, I have a home bridge plugin [here](https://github.com/kuestess/homebridge-platform-insteon).  Not nearly as full featured, but works at least as well as my Hub Pro.  A local control version is [here](https://github.com/kuestess/homebridge-platform-insteon), but severely limited because the Hub can only handle a single connection.  I'm not a node or javascript developer, and I'm sure it can be improved (perhaps by integrating this package).

**Comment by kuestess** [comment]
I've uploaded a new version of my Homebridge plugin that leverages `home-controller` to control Insteon devices.  You can find it [here](https://github.com/kuestess/homebridge-platform-insteonlocal).  It works at least as well as the Hub Pro and also updates state on manual operation.  Only supports lighting right now, but plan to add additional device types in the future.

**Comment by siburny** [comment]
I will close this ticket, but we need to add a note in the `readme` about this plugin.
